DROP TABLE IF EXISTS PRODUCTS;

CREATE TABLE PRODUCTS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  PRODUCT_TYPE VARCHAR(50) NOT NULL,
  PROPERTY VARCHAR(50) NOT NULL,
  COLOR VARCHAR(50),
  GB_LIMIT INT,
  PRICE DECIMAL ,
  STREET VARCHAR(50) NOT NULL,
  CITY VARCHAR(50) NOT NULL
);